# Generated by Django 2.1.1 on 2018-09-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Название')),
                ('country', models.CharField(max_length=254, verbose_name='Страна')),
                ('region', models.CharField(max_length=254, verbose_name='Область')),
                ('city', models.CharField(max_length=254, verbose_name='Город')),
                ('street', models.CharField(max_length=254, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=64, null=True, verbose_name='Дом')),
                ('office', models.CharField(blank=True, max_length=64, null=True, verbose_name='Офис')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='NewContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=254, verbose_name='Телефон')),
                ('interest', models.TextField(max_length=254, verbose_name='Интерес')),
                ('company', models.ManyToManyField(to='contacts.Company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Новый контакт',
                'verbose_name_plural': 'Новые контакты',
            },
        ),
    ]
