# Generated by Django 2.1.1 on 2018-09-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=156, verbose_name='Название компании '),
        ),
    ]
